language: python
sudo: false

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-django18
    - python: 3.3
      env: TOX_ENV=py33-django18
    - python: 3.4
      env: TOX_ENV=py34-django18
    - python: 3.5
      env: TOX_ENV=py35-django18
    - python: 2.7
      env: TOX_ENV=py27-django19
    - python: 3.4
      env: TOX_ENV=py34-django19
    - python: 3.5
      env: TOX_ENV=py35-django19

install:
  - pip install tox

before_script:
  - psql -c 'create database netfields;' -U postgres

script:
  - tox -e $TOX_ENV
